#!/usr/bin/env node
// Balsm-AI sync: generate universal AGENTS.md from canonical sources.
// Single source of truth -> adapters. Today: AGENTS.md baseline (read by
// Cursor, OpenCode, Antigravity, Gemini, Codex; bridgeable to Copilot).
//
// Usage:
//   node sync.mjs                 # write Balsm-AI/AGENTS.md
//   node sync.mjs --distribute    # also copy AGENTS.md into every sibling Balsm repo root
//   node sync.mjs --check         # exit 1 if AGENTS.md is stale (CI guard)

import { readFileSync, writeFileSync, readdirSync, existsSync, statSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(fileURLToPath(import.meta.url));
const WORKSPACE = dirname(ROOT); // /Volumes/Dev/Balsm
const args = new Set(process.argv.slice(2));

const RULES_DIR = join(ROOT, "canonical", "rules");
const SKILLS_DIR = join(ROOT, "plugin", "skills");
const COMMANDS_DIR = join(ROOT, "plugin", "commands");
const AGENTS_OUT = join(ROOT, "AGENTS.md");

// --- minimal YAML frontmatter reader (handles folded multi-line values) ---
function frontmatter(md) {
  const m = md.match(/^---\n([\s\S]*?)\n---/);
  if (!m) return {};
  const out = {};
  let key = null;
  for (const line of m[1].split("\n")) {
    const kv = line.match(/^([A-Za-z0-9_-]+):\s?(.*)$/);
    if (kv) {
      key = kv[1];
      out[key] = kv[2];
    } else if (key && /^\s+\S/.test(line)) {
      // continuation of a folded scalar
      out[key] = (out[key] + " " + line.trim()).trim();
    } else {
      key = null;
    }
  }
  return out;
}

function listDirs(p) {
  if (!existsSync(p)) return [];
  return readdirSync(p).filter((d) => {
    try { return statSync(join(p, d)).isDirectory(); } catch { return false; }
  }).sort();
}

function listMd(p) {
  if (!existsSync(p)) return [];
  return readdirSync(p).filter((f) => f.endsWith(".md")).sort();
}

// --- gather ---
const rules = listMd(RULES_DIR)
  .map((f) => readFileSync(join(RULES_DIR, f), "utf8").trim())
  .join("\n\n");

const skills = listDirs(SKILLS_DIR).map((name) => {
  const sk = join(SKILLS_DIR, name, "SKILL.md");
  const fm = existsSync(sk) ? frontmatter(readFileSync(sk, "utf8")) : {};
  return {
    name: fm.name || name,
    description: (fm.description || "").replace(/\s+/g, " ").trim(),
    rel: `plugin/skills/${name}/SKILL.md`, // relative to Balsm-AI root
  };
});

const commands = listMd(COMMANDS_DIR).map((f) => {
  const fm = frontmatter(readFileSync(join(COMMANDS_DIR, f), "utf8"));
  return { name: f.replace(/\.md$/, ""), description: (fm.description || "").trim() };
});

// --- render AGENTS.md ---
// pathPrefix: prepended to each skill's path so refs resolve from the file's
// own location. "" for Balsm-AI's own AGENTS.md; "../Balsm-AI/" for sibling repos.
function render(pathPrefix) {
  const lines = [];
  lines.push("<!-- GENERATED by Balsm-AI/sync.mjs — edit canonical/ + plugin/, then re-run. Do not edit by hand. -->");
  lines.push("# Balsm — Agent Instructions\n");
  lines.push("Shared instructions for any AI coding agent (Claude Code, Cursor, Copilot, Windsurf, OpenCode, Antigravity, Gemini, Codex). Source of truth: the `Balsm-AI` repo.\n");

  lines.push(rules + "\n");

  lines.push("## Security skills — on-demand index\n");
  lines.push("These are deep how-to playbooks. Do NOT load them all. When a task matches one, open the file at its path and follow it. Paths assume the Balsm repos sit side by side under one workspace folder.\n");
  lines.push("| Skill | When to use | File |");
  lines.push("|---|---|---|");
  for (const s of skills) {
    const desc = s.description.length > 140 ? s.description.slice(0, 137) + "…" : s.description;
    lines.push(`| ${s.name} | ${desc} | \`${pathPrefix}${s.rel}\` |`);
  }
  lines.push("");

  if (commands.length) {
    lines.push("## Shared commands\n");
    lines.push("Reusable prompt workflows (native slash commands in Claude Code; reference the file content in other tools).\n");
    for (const c of commands) lines.push(`- **${c.name}** — ${c.description}`);
    lines.push("");
  }

  lines.push("---");
  lines.push(`<sub>Generated from ${skills.length} skills + ${commands.length} commands. Update: edit \`Balsm-AI/canonical/\` or \`Balsm-AI/plugin/\`, run \`node Balsm-AI/sync.mjs --distribute\`.</sub>`);

  return lines.join("\n") + "\n";
}

const content = render("");                 // Balsm-AI's own copy
const siblingContent = render("../Balsm-AI/"); // copies placed in sibling repos

// --- check mode ---
if (args.has("--check")) {
  const cur = existsSync(AGENTS_OUT) ? readFileSync(AGENTS_OUT, "utf8") : "";
  if (cur !== content) {
    console.error("AGENTS.md is stale — run: node Balsm-AI/sync.mjs");
    process.exit(1);
  }
  console.log("AGENTS.md up to date.");
  process.exit(0);
}

writeFileSync(AGENTS_OUT, content);
console.log(`wrote ${AGENTS_OUT} (${skills.length} skills, ${commands.length} commands)`);

// --- distribute to sibling repos ---
if (args.has("--distribute")) {
  const skip = new Set(["Balsm-AI", "assets"]);
  let n = 0;
  for (const d of listDirs(WORKSPACE)) {
    if (skip.has(d) || d.startsWith(".")) continue;
    const repo = join(WORKSPACE, d);
    if (!existsSync(join(repo, ".git"))) continue; // only real repos
    writeFileSync(join(repo, "AGENTS.md"), siblingContent);
    console.log(`  → ${d}/AGENTS.md`);
    n++;
  }
  console.log(`distributed to ${n} repos`);
}
